// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAriD_Pd7uoRAbeVx1eCXkkktBjHj7N4Vo',
    appId: '1:420640866742:web:c6babaf7cef01185f20117',
    messagingSenderId: '420640866742',
    projectId: 'flutter-project-eff01',
    authDomain: 'flutter-project-eff01.firebaseapp.com',
    storageBucket: 'flutter-project-eff01.firebasestorage.app',
    measurementId: 'G-GFRRXN7DPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtUfJmHxFFEMi_4Xv9zfLaBEy7mrCYyKE',
    appId: '1:420640866742:android:7cc0ee059abc17c4f20117',
    messagingSenderId: '420640866742',
    projectId: 'flutter-project-eff01',
    storageBucket: 'flutter-project-eff01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxoivHMuE1t2oNCQnjhHSPCIj5PdVMoqo',
    appId: '1:420640866742:ios:df3921d7c9b3c8bbf20117',
    messagingSenderId: '420640866742',
    projectId: 'flutter-project-eff01',
    storageBucket: 'flutter-project-eff01.firebasestorage.app',
    iosBundleId: 'com.example.tripify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxoivHMuE1t2oNCQnjhHSPCIj5PdVMoqo',
    appId: '1:420640866742:ios:df3921d7c9b3c8bbf20117',
    messagingSenderId: '420640866742',
    projectId: 'flutter-project-eff01',
    storageBucket: 'flutter-project-eff01.firebasestorage.app',
    iosBundleId: 'com.example.tripify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAriD_Pd7uoRAbeVx1eCXkkktBjHj7N4Vo',
    appId: '1:420640866742:web:05f9398eaa5d55a4f20117',
    messagingSenderId: '420640866742',
    projectId: 'flutter-project-eff01',
    authDomain: 'flutter-project-eff01.firebaseapp.com',
    storageBucket: 'flutter-project-eff01.firebasestorage.app',
    measurementId: 'G-TL8HBX8F4M',
  );
}
