// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEiILafLyoCX90a4pVN3yk9k9e4BbMs3Y',
    appId: '1:455429171819:web:d572352055eba658801f2e',
    messagingSenderId: '455429171819',
    projectId: 'tripify-9e595',
    authDomain: 'tripify-9e595.firebaseapp.com',
    storageBucket: 'tripify-9e595.firebasestorage.app',
    measurementId: 'G-QB503YTXLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrf3omU5FzNQiYAS3yTfShUd7YWJNBoOk',
    appId: '1:455429171819:android:2091be21e223033d801f2e',
    messagingSenderId: '455429171819',
    projectId: 'tripify-9e595',
    storageBucket: 'tripify-9e595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXMKJKCgp7EU3eSldI3ZbAgHHJoKwhc6s',
    appId: '1:455429171819:ios:c478ec01a32351f3801f2e',
    messagingSenderId: '455429171819',
    projectId: 'tripify-9e595',
    storageBucket: 'tripify-9e595.firebasestorage.app',
    iosBundleId: 'com.example.tripify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXMKJKCgp7EU3eSldI3ZbAgHHJoKwhc6s',
    appId: '1:455429171819:ios:c478ec01a32351f3801f2e',
    messagingSenderId: '455429171819',
    projectId: 'tripify-9e595',
    storageBucket: 'tripify-9e595.firebasestorage.app',
    iosBundleId: 'com.example.tripify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEiILafLyoCX90a4pVN3yk9k9e4BbMs3Y',
    appId: '1:455429171819:web:e9f77d5b8dbe3b95801f2e',
    messagingSenderId: '455429171819',
    projectId: 'tripify-9e595',
    authDomain: 'tripify-9e595.firebaseapp.com',
    storageBucket: 'tripify-9e595.firebasestorage.app',
    measurementId: 'G-SSZ859W6BD',
  );
}
